server {
    listen 81;  # ← Порт в контейнере (т.к. -p 80:81)

    location / {
        fastcgi_pass 127.0.0.1:8080;
        include fastcgi_params;
    }

    location /status {
        stub_status on;
        access_log off;
        allow all;
    }
}